FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production

COPY .next/standalone/ ./
COPY prisma/ ./prisma/

RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs && \
    chown -R nextjs:nodejs /app

EXPOSE 3000
ENV PORT=3000 HOSTNAME="0.0.0.0"

USER nextjs
CMD ["sh", "-c", "npx prisma db push --skip-generate 2>/dev/null; node server.js"]
